build:
  nodes:
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --testdox --verbose
            coverage:
              file: coverage-report/coverage.xml
              format: clover
